# This SPARQL query ensures that terms do not have one or more definitions.

PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?term (COUNT(?definition) AS ?definitionCount)
WHERE {
  ?term cco:definition|skos:definition ?definition .
}
GROUP BY ?term
HAVING (COUNT(?definition) > 1)
